name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  check-install:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
  docker:
    runs-on: ubuntu-latest
    needs: check-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.sha }}

      - name: Deploy to ecs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.ALIYUN_HOST }}
          username: ${{ vars.ALIYUN_USERNAME }}
          key: ${{ secrets.ALIYUN_SEC }}
          port: ${{ vars.ALIYUN_SERVER_SSH_PORT }}
          script: |
            kubectl set image deployment/nginx-deployment1 nginx=${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.sha }}

