name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  check-install:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build
  docker:
    runs-on: ubuntu-latest
    needs: check-install
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # username: ${{ secrets.DOCKER_HUB_USERNAME }}
          # password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          username: 110477lyj
          password: 110477lyj

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # tags: |
          #   ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ github.sha }}
          tags: |
            110477lyj/test:${{ github.sha }}

      - name: Deploy to ecs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.ALIYUN_ECS_HOST }}
          username: ${{ vars.ALIYUN_ECS_USER }}
          key: ${{ secrets.ALIYUN_ECS_SEC }}
          # port: ${{ vars.ALIYUN_SERVER_SSH_PORT }}
          port: 22
          script: |
            sed 's/nginx-image/110477lyj/test:${{ github.sha }}/g' ./service.yaml
            kubectl apply -f ./service.yaml

